from __future__ import annotations

import json
import threading
import time
import urllib.error
import urllib.request
from typing import Any, Protocol, Sequence

from my_agent.config import AgentConfig
from my_agent.llm.types import ChatResponse, ChatUsage, LLMToolCall, MessageLike, messages_to_openai


class AgentLLM(Protocol):
    supports_tools: bool

    def chat(self, messages: list[MessageLike], tools: list[dict[str, Any]] | None = None) -> ChatResponse:
        ...


def build_llm(config: AgentConfig) -> AgentLLM:
    """Backward-compatible alias for the shared policy builder."""

    return build_policy(config)


def build_policy(config: AgentConfig) -> AgentLLM:
    config.require_valid_formal_evolver()
    if config.memory_evolver_mode == "formal":
        from my_agent.policy.runtime_validation import require_formal_policy
        from my_agent.policy.transformers_policy import TransformersPolicy

        policy = TransformersPolicy.from_config(config)
        require_formal_policy(config, policy)
        return policy
    config.require_valid_provider()
    if config.use_fake_llm:
        return FakeLLM()
    if config.provider == "openai":
        config.require_api_key()
        return OpenAICompatibleLLM(config)
    raise RuntimeError(f"Unsupported LLM provider: {config.provider}")


class FakeLLM:
    """Deterministic local model used by tests and smoke runs."""

    supports_tools = True

    def __init__(
        self,
        chat_responses: Sequence[ChatResponse | str] | None = None,
    ):
        self._chat_responses = list(chat_responses or [])
        self._chat_turn = 0
        self._plan_task_turns: dict[str, int] = {}
        self._lock = threading.Lock()

    def chat(self, messages: list[MessageLike], tools: list[dict[str, Any]] | None = None) -> ChatResponse:
        with self._lock:
            return self._chat_unlocked(messages, tools)

    def _chat_unlocked(self, messages: list[MessageLike], tools: list[dict[str, Any]] | None = None) -> ChatResponse:
        if self._chat_responses:
            response = self._chat_responses.pop(0)
            if isinstance(response, ChatResponse):
                return response
            return ChatResponse(content=response, finish_reason="stop")
        if tools is None:
            prompt_text = _messages_text(messages).lower()
            if _is_team_planner_prompt(messages):
                return ChatResponse(content=_fake_team_plan_json(prompt_text), finish_reason="stop")
            if _is_team_reviewer_prompt(messages):
                return ChatResponse(content=_fake_team_review_json(prompt_text), finish_reason="stop")
            if "planner for a coding agent" in prompt_text:
                return ChatResponse(content=_fake_plan_json(prompt_text), finish_reason="stop")
            if "请压缩以下 agent 对话片段" in prompt_text:
                return ChatResponse(content="Compressed map summary generated by FakeLLM.", finish_reason="stop")
            if "请合并以下多个对话摘要" in prompt_text:
                return ChatResponse(content="Compressed reduce summary generated by FakeLLM.", finish_reason="stop")
            if "只输出 json 数组" in prompt_text and "稳定事实" in prompt_text:
                return ChatResponse(content=_fake_fact_json(prompt_text), finish_reason="stop")
            if "summarize conversation history" in prompt_text:
                return ChatResponse(content="Compressed summary generated by FakeLLM.", finish_reason="stop")
            return ChatResponse(content="FakeLLM response.", finish_reason="stop")
        plan_task = _plan_task_key(messages)
        if plan_task is not None:
            task_id, task_type = plan_task
            turn = self._plan_task_turns.get(task_id, 0) + 1
            self._plan_task_turns[task_id] = turn
            return _plan_task_response(task_type, turn)
        self._chat_turn += 1
        if self._chat_turn == 1:
            return _tool_chat_response("retrieve_context", {"query": "subtract", "top_k": 3})
        if self._chat_turn == 2:
            return _tool_chat_response("read_file", {"path": "calculator.py", "limit": 12000})
        if self._chat_turn == 3:
            old = 'def subtract(a: int, b: int) -> int:\n    """Return a minus b."""\n    return a + b'
            new = 'def subtract(a: int, b: int) -> int:\n    """Return a minus b."""\n    return a - b'
            return _tool_chat_response("replace_in_file", {"path": "calculator.py", "old": old, "new": new})
        if self._chat_turn == 4:
            return _tool_chat_response("run_tests", {})
        if self._chat_turn == 5:
            return _tool_chat_response("git_diff", {})
        return _tool_chat_response(
            "finish",
            {"summary": "Updated subtract to return the first number minus the second number and ran tests."},
        )


class OpenAICompatibleLLM:
    """Small OpenAI-compatible chat-completions client implemented with stdlib HTTP."""

    supports_tools = True

    def __init__(self, config: AgentConfig, timeout: int = 60, max_retries: int = 2):
        config.require_api_key()
        self.api_key = config.api_key
        self.base_url = (config.base_url or "https://api.openai.com/v1").rstrip("/")
        self.model = config.model
        self.temperature = config.temperature
        self.reasoning_effort = config.reasoning_effort
        self.timeout = timeout
        self.max_retries = max(0, max_retries)

    def chat(self, messages: list[MessageLike], tools: list[dict[str, Any]] | None = None) -> ChatResponse:
        payload: dict[str, Any] = {
            "model": self.model,
            "messages": messages_to_openai(messages),
            "temperature": self.temperature,
        }
        if self.reasoning_effort is not None:
            payload["reasoning_effort"] = self.reasoning_effort
        if tools is not None:
            payload["tools"] = tools
        body = self._post_chat_completion(payload)
        try:
            parsed = json.loads(body)
            return ChatResponse.from_openai_payload(parsed)
        except (ValueError, json.JSONDecodeError) as exc:
            raise RuntimeError(f"LLM response could not be parsed: {_excerpt(body)}") from exc

    def _chat(self, messages: list[dict[str, str]], tools: list[dict[str, Any]] | None = None) -> str:
        response = self.chat(messages, tools=tools)
        if not response.content:
            raise RuntimeError("LLM response message content was empty.")
        return response.content

    def _post_chat_completion(self, payload: dict[str, Any]) -> str:
        request = urllib.request.Request(
            f"{self.base_url}/chat/completions",
            data=json.dumps(payload).encode("utf-8"),
            headers={
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json",
                "User-Agent": "AgentCli/1.0",
            },
            method="POST",
        )
        attempts = self.max_retries + 1
        last_error = ""
        for attempt in range(attempts):
            try:
                with urllib.request.urlopen(request, timeout=self.timeout) as response:
                    return response.read().decode("utf-8")
            except urllib.error.HTTPError as exc:
                error_body = exc.read().decode("utf-8", errors="replace")
                last_error = f"LLM request failed with HTTP {exc.code}: {_excerpt(error_body)}"
                if not _is_retryable_http_error(exc.code) or attempt == attempts - 1:
                    raise RuntimeError(last_error) from exc
            except urllib.error.URLError as exc:
                last_error = f"LLM request failed: {exc.reason}"
                if attempt == attempts - 1:
                    raise RuntimeError(last_error) from exc
            except TimeoutError as exc:
                last_error = f"LLM request timed out: {exc}"
                if attempt == attempts - 1:
                    raise RuntimeError(last_error) from exc
            time.sleep(min(0.25 * (2**attempt), 1.0))
        raise RuntimeError(last_error or "LLM request failed.")


def _is_retryable_http_error(status_code: int) -> bool:
    return status_code == 429 or status_code >= 500


def _tool_chat_response(tool: str, arguments: dict[str, object]) -> ChatResponse:
    arguments_json = json.dumps(arguments, ensure_ascii=False)
    return ChatResponse(
        content="",
        finish_reason="tool_calls",
        tool_calls=[
            LLMToolCall(
                id=f"call_{tool}",
                name=tool,
                arguments=dict(arguments),
                arguments_json=arguments_json,
            )
        ],
    )


def _fake_plan_json(prompt_text: str) -> str:
    if "subtract" in prompt_text or "修复" in prompt_text:
        tasks = [
            {
                "id": "inspect",
                "title": "Inspect calculator",
                "description": "Inspect the calculator implementation and tests related to subtract.",
                "type": "inspect",
                "depends_on": [],
                "acceptance": "Relevant implementation and tests have been inspected.",
            },
            {
                "id": "edit",
                "title": "Fix subtract",
                "description": "Fix subtract so it returns the first number minus the second number.",
                "type": "edit",
                "depends_on": ["inspect"],
                "acceptance": "subtract returns a - b.",
            },
            {
                "id": "test",
                "title": "Run tests",
                "description": "Run the configured test command and report the result.",
                "type": "test",
                "depends_on": ["edit"],
                "acceptance": "Relevant tests pass.",
            },
        ]
    else:
        tasks = [
            {
                "id": "inspect",
                "title": "Inspect repository",
                "description": "Inspect the repository context needed for the user request.",
                "type": "inspect",
                "depends_on": [],
                "acceptance": "The requested context has been inspected.",
            }
        ]
    return json.dumps({"summary": "Plan generated by FakeLLM.", "tasks": tasks}, ensure_ascii=False)


def _fake_team_plan_json(prompt_text: str) -> str:
    if "subtract" in prompt_text or "修复" in prompt_text:
        steps = [
            {
                "id": "inspect",
                "title": "Inspect calculator",
                "description": "Inspect the calculator implementation and tests related to subtract.",
                "type": "inspect",
                "dependencies": [],
                "acceptance": "Relevant implementation and tests have been inspected.",
            },
            {
                "id": "edit",
                "title": "Fix subtract",
                "description": "Fix subtract so it returns the first number minus the second number.",
                "type": "edit",
                "dependencies": ["inspect"],
                "acceptance": "subtract returns a - b.",
            },
            {
                "id": "test",
                "title": "Run tests",
                "description": "Run the configured test command and report the result.",
                "type": "test",
                "dependencies": ["edit"],
                "acceptance": "Relevant tests pass.",
            },
        ]
    else:
        steps = [
            {
                "id": "inspect",
                "title": "Inspect repository",
                "description": "Inspect the repository context needed for the user request.",
                "type": "inspect",
                "dependencies": [],
                "acceptance": "The requested context has been inspected.",
            }
        ]
    return json.dumps({"summary": "Team plan generated by FakeLLM.", "steps": steps}, ensure_ascii=False)


def _fake_team_review_json(prompt_text: str) -> str:
    approved = "worker result:\nno worker result was provided" not in prompt_text
    summary = "FakeLLM reviewer approved the worker result." if approved else "FakeLLM reviewer found no worker result."
    issues = [] if approved else ["Worker result is empty."]
    return json.dumps({"approved": approved, "summary": summary, "issues": issues, "suggestions": []}, ensure_ascii=False)


def _fake_fact_json(prompt_text: str) -> str:
    facts: list[dict[str, object]] = []
    if "回答中文" in prompt_text:
        facts.append({"content": "用户偏好：回答中文，先给结论", "scope": "project", "confidence": 0.95})
    if "agentcli" in prompt_text:
        facts.append({"content": "项目 AgentCli 使用 Python src 布局", "scope": "project", "confidence": 0.85})
    return json.dumps(facts, ensure_ascii=False)


def _plan_task_response(task_type: str, turn: int) -> ChatResponse:
    if task_type == "inspect":
        if turn == 1:
            return _tool_chat_response("retrieve_context", {"query": "subtract", "top_k": 3})
        if turn == 2:
            return _tool_chat_response("read_file", {"path": "calculator.py", "limit": 12000})
        return _tool_chat_response("finish", {"summary": "Inspected calculator implementation and tests."})

    if task_type == "edit":
        if turn == 1:
            return _tool_chat_response("read_file", {"path": "calculator.py", "limit": 12000})
        if turn == 2:
            old = 'def subtract(a: int, b: int) -> int:\n    """Return a minus b."""\n    return a + b'
            new = 'def subtract(a: int, b: int) -> int:\n    """Return a minus b."""\n    return a - b'
            return _tool_chat_response("replace_in_file", {"path": "calculator.py", "old": old, "new": new})
        if turn == 3:
            return _tool_chat_response("run_tests", {})
        return _tool_chat_response(
            "finish",
            {"summary": "Updated subtract to return the first number minus the second number and ran tests."},
        )

    if task_type == "test":
        if turn == 1:
            return _tool_chat_response("run_tests", {})
        return _tool_chat_response("finish", {"summary": "Ran the configured tests."})

    if turn == 1:
        return _tool_chat_response("retrieve_context", {"query": "subtract", "top_k": 3})
    if turn == 2:
        return _tool_chat_response("read_file", {"path": "calculator.py", "limit": 12000})
    return _tool_chat_response("finish", {"summary": "Completed the plan task."})


def _plan_task_key(messages: list[MessageLike]) -> tuple[str, str] | None:
    text = _messages_text(messages)
    task_id = _line_value(text, "Current task id:")
    task_type = _line_value(text, "Current task type:")
    if not task_id and "Current step:" in text:
        task_id = _line_value(text, "- id:")
        task_type = _line_value(text, "- type:")
    if not task_id:
        return None
    return task_id, (task_type or "analysis").strip().lower()


def _line_value(text: str, prefix: str) -> str:
    for line in text.splitlines():
        if line.startswith(prefix):
            return line.removeprefix(prefix).strip()
    return ""


def _is_team_planner_prompt(messages: list[MessageLike]) -> bool:
    system_prompt = _first_system_message_text(messages).lower()
    return (
        "you are the planner in a multi-agent coding team" in system_prompt
        and "return only json with this shape" in system_prompt
        and '"steps"' in system_prompt
    )


def _is_team_reviewer_prompt(messages: list[MessageLike]) -> bool:
    system_prompt = _first_system_message_text(messages).lower()
    return (
        "you are a reviewer sub-agent in a multi-agent coding team" in system_prompt
        and "return only json with this shape" in system_prompt
        and '"approved"' in system_prompt
    )


def _first_system_message_text(messages: list[MessageLike]) -> str:
    for message in messages:
        role = ""
        content: object = ""
        if isinstance(message, dict):
            role = str(message.get("role", ""))
            content = message.get("content", "")
        else:
            role = message.role
            content = message.content
        if role == "system" and isinstance(content, str):
            return content
    return ""


def _messages_text(messages: list[MessageLike]) -> str:
    rendered: list[str] = []
    for message in messages:
        if isinstance(message, dict):
            content = message.get("content", "")
        else:
            content = message.content
        if isinstance(content, str):
            rendered.append(content)
    return "\n".join(rendered)


def _excerpt(text: str, limit: int = 500) -> str:
    return text if len(text) <= limit else text[:limit] + "\n... truncated"


__all__ = [
    "AgentLLM",
    "ChatResponse",
    "ChatUsage",
    "FakeLLM",
    "MessageLike",
    "OpenAICompatibleLLM",
    "build_llm",
    "build_policy",
]
